# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nqn7mi's Blog
subtitle: 个人博客
keywords: blog, 博客, 编程
description: >- # this means to ignore newlines until "baseurl:"
  这里是 Nqn7mi 的个人博客，主要分享编程、算法和生活感悟。
email: nightrav3n@foxmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nqn7mi-mylove.github.io" # the base hostname & protocol for your site
github_username: Nqn7mi
author: Nqn7mi
avatar: /assets/imgs/avatar.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 评论系统设置（可选）
comments: true
disqus_shortname: # 你的disqus账号

# Google Analytics（可选）
google_analytics: # 你的Google Analytics跟踪ID

# 导航菜单
menu:
  -
    page: 主页
    directory: 
    icon: icon-home
  -
    page: 归档
    directory: archives/
    icon: icon-archive
  -
    page: 分类
    directory: category/
    icon: icon-category
  -
    page: 标签
    directory: tags/
    icon: icon-tags
  -
    page: 关于
    directory: about/
    icon: icon-about

navigation:
  - title: 首页
    url: /
  - title: 归档
    url: /archives/
  - title: 分类
    url: /categories/
  - title: 关于
    url: /about/

# 社交链接
social:
  github: https://github.com/Nqn7mi
  email: nightrav3n@foxmail.com

# 摘要相关配置
excerpt_separator: <!--more-->
excerpt_length: 150    # 摘要的最大字符数
show_excerpts: true   # 在首页显示摘要

# 其他设置
future: true
